# Generated by Django 6.0.6 on 2026-06-12 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('expense_type', models.CharField(choices=[('rent', 'کرایه دوکان'), ('electricity', 'بل برق'), ('daily', 'مصارف روزانه'), ('personal', 'مصارف شخصی')], max_length=20, verbose_name='نوع مصرف')),
                ('currency', models.CharField(choices=[('AFN', 'افغانی'), ('USD', 'دالر')], default='AFN', max_length=3, verbose_name='واحد پول')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'مصرف مالی',
                'verbose_name_plural': 'مصارف مالی',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Consumption',
        ),
    ]
