# Generated by Django 6.0.6 on 2026-06-12 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_category'),
        ('purchases', '0001_initial'),
        ('suppliers', '0002_alter_supplier_options_remove_supplier_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'ordering': ['-date'], 'verbose_name': 'فاکتور خرید', 'verbose_name_plural': 'فاکتورهای خرید'},
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='description',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='currency',
            field=models.CharField(choices=[('AFN', 'افغانی'), ('USD', 'دالر')], default='AFN', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'نقد'), ('CREDIT', 'قرض')], default='CASH', max_length=10, verbose_name='روش پرداخت'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='باقیمانده'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ پرداختی'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='تهیه\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseinvoice', verbose_name='فاکتور'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='کالا'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت واحد'),
        ),
    ]
