# Generated by Django 6.0.6 on 2026-06-12 06:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_category'),
        ('purchases', '0002_alter_purchaseinvoice_options_and_more'),
        ('suppliers', '0002_alter_supplier_options_remove_supplier_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={},
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='currency',
            field=models.CharField(choices=[('AFN', 'افغانی'), ('USD', 'دالر')], default='AFN', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'نقد'), ('CREDIT', 'قرض')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseinvoice'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=datetime.date(2026, 6, 12), max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
