# Generated by Django 6.0.6 on 2026-06-12 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_purchaseinvoice_options_and_more'),
        ('settings_app', '0003_alter_currency_code_alter_currency_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='settings_app.currency', verbose_name='واحد پول'),
        ),
    ]
