# Generated by Django 6.0.6 on 2026-06-11 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miscperson',
            options={'verbose_name': 'شخص متفرقه', 'verbose_name_plural': 'اشخاص متفرقه'},
        ),
        migrations.RemoveField(
            model_name='miscperson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='miscperson',
            name='opening_balance',
        ),
        migrations.AddField(
            model_name='miscperson',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='miscperson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miscperson',
            name='currency',
            field=models.CharField(choices=[('AFN', 'افغانی'), ('USD', 'دالر')], default='AFN', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AlterField(
            model_name='miscperson',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام شخص'),
        ),
        migrations.AlterField(
            model_name='miscperson',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس'),
        ),
    ]
