# Generated by Django 6.0.6 on 2026-06-12 03:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_opening_balance'),
        ('misc_persons', '0002_alter_miscperson_options_and_more'),
        ('suppliers', '0002_alter_supplier_options_remove_supplier_email_and_more'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialtransaction',
            options={'ordering': ['-transaction_date'], 'verbose_name': 'تراکنش مالی', 'verbose_name_plural': 'تراکنش\u200cهای مالی'},
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='transaction_date',
            field=models.DateField(default=datetime.date(2026, 6, 12), help_text='به صورت شمسی وارد کنید (مثال: 1402/10/15)', verbose_name='تاریخ تراکنش'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در سیستم'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='misc_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc_persons.miscperson', verbose_name='شخص متفرقه'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='person_type',
            field=models.CharField(choices=[('CUSTOMER', 'مشتری'), ('SUPPLIER', 'تهیه\u200cکننده'), ('MISC', 'متفرقه')], max_length=10, verbose_name='نوع شخص'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier', verbose_name='تهیه\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'واریز (جمع به حساب)'), ('OUT', 'برداشت از حساب')], max_length=3, verbose_name='نوع تراکنش'),
        ),
    ]
