# Generated by Django 6.0.6 on 2026-06-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_financialtransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='transaction_date',
            field=models.DateField(verbose_name='تاریخ تراکنش'),
        ),
    ]
