# Generated by Django 6.0.6 on 2026-06-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_email_customer_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='opening_balance',
        ),
    ]
