# Generated by Django 6.0.6 on 2026-06-12 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_opening_balance'),
        ('settings_app', '0003_alter_currency_code_alter_currency_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings_app.currency', verbose_name='واحد پول'),
        ),
    ]
