# Generated by Django 6.0.6 on 2026-06-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='کد (مثلاً AFN, USD)')),
                ('name', models.CharField(max_length=50, verbose_name='نام واحد پول')),
                ('symbol', models.CharField(max_length=5, verbose_name='نماد (مثلاً ؋, $)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'واحد پول',
                'verbose_name_plural': 'واحدهای پول',
            },
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='فروشگاه من', max_length=200, verbose_name='نام فروشگاه')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('footer_text', models.TextField(blank=True, verbose_name='متن پایانی فاکتور')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'اطلاعات فروشگاه',
                'verbose_name_plural': 'اطلاعات فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام واحد')),
                ('symbol', models.CharField(blank=True, max_length=10, verbose_name='نماد (اختیاری)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'واحد اندازه\u200cگیری',
                'verbose_name_plural': 'واحدهای اندازه\u200cگیری',
            },
        ),
        migrations.DeleteModel(
            name='AppSetting',
        ),
    ]
