# Generated by Django 6.0.6 on 2026-06-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_currency_shopinfo_unitofmeasure_delete_appsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=5, verbose_name='نماد'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, verbose_name='نماد'),
        ),
    ]
