# Generated by Django 6.0.6 on 2026-06-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_alter_currency_code_alter_currency_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره واتساپ'),
        ),
    ]
