# Generated by Django 6.0.6 on 2026-06-11 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ فروش')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='نام مشتری')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ کل')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ پرداختی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش\u200cها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت واحد')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت کل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='محصول')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'آیتم فروش',
                'verbose_name_plural': 'آیتم\u200cهای فروش',
            },
        ),
    ]
