# Generated by Django 6.0.6 on 2026-06-12 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_opening_balance'),
        ('sales', '0002_alter_saleitem_options_alter_sale_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(choices=[('AFN', 'افغانی'), ('USD', 'دالر')], default='AFN', max_length=3),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'نقد'), ('CREDIT', 'قرض')], default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تراکنش'),
        ),
    ]
